export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TEST = "SET_CURRENT_TEST";
export const FETCH_TEST_LIST = "FETCH_TEST_LIST";
export const CREATE_TEST = "CREATE_TEST";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const FETCH_QUESTION_DETAILS = "FETCH_QUESTION_DETAILS";
export const SET_CURRENT_CODE = "SET_CURRENT_CODE";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
