export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TEST_LIST = "SET_TEST_LIST";
export const CREATE_TEST = "CREATE_TEST";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const ADD_QUESTION_DETAILS = "ADD_QUESTION_DETAILS";
export const SET_CURRENT_CODE = "SET_CURRENT_CODE";
